sudo: true
language: node_js
node_js:
  - 14.9.0 # use nodejs v10 LTS
cache: npm
install:
  - rm package-lock.json
  - npm install
branches:
  only:
    - hexo # build master branch only
script:
  - hexo clean
  - hexo generate # generate static files
deploy:
  provider: pages
  skip-cleanup: false
  github-token: $GH_TOKEN
  keep-history: true
  on:
    branch: hexo
  local-dir: public
