sudo: true
language: node_js
node_js:
  - 14.9.0 # use nodejs v10 LTS
cache: npm
install:
  - npm install hexo-cli -g
  - npm install hexo --save
  - rm package-lock.json
  - npm install
  - git clone -b v6.6.0 git@github.com:theme-next/hexo-theme-next.git themes/next
  - cp _next_config.yml themes/next/_config.yml
branches:
  only:
    - hexo # build master branch only
script:
  - hexo clean
  - hexo generate # generate static files
deploy:
  provider: pages
  skip-cleanup: false
  github-token: $GH_TOKEN
  keep-history: true
  on:
    branch: hexo
  local-dir: public
