sudo: true
language: node_js
node_js:
  - 13.3.0 # use nodejs v10 LTS
cache: npm
install:
  - rm package-lock.json
  - npm install
  - cp _next_config.yml themes/next/_config.yml
branches:
  only:
    - hexo
script:
  - hexo clean
  - hexo generate 
deploy:
  provider: pages
  skip-cleanup: false
  github-token: $GH_TOKEN
  keep-history: false
  target_branch: gh-pages
  on:
    branch: hexo
